[package]
name = "cat-fax"
version = "0.1.0"
edition = "2021"
authors = ["eric (sk3pz) skepz.dev@gmail.com"]
description = "Like Cowsay, but with factually accurate cat facts!"

[dependencies]
better_term = "1.0.4"
rand = "*"
glutin = "*"
gfx = "*"
gfx_glyph = "*"
glyph_brush = "*"
old_school_gfx_glutin_ext = "*"